### ISSUE TITLE
Key Handlers don't respect modifiers

### ISSUE THREAD

**Issue by tcbyrd** [generative-music/generative.fm#139]
The shortcuts defined [here](https://github.com/generative-music/generative.fm/blob/d92cdfdab6e3b7bc56a91e0e6ccac83e6bbe155d/src/store/middleware/shortcuts.middleware.js#L9-L12) aren't respecting key modifiers. I noticed this because I generally pull up the site and then do `Apple + M` to minimize it, but instead of minimizing, the track mutes. The same is also true for back/forward navigation not working because left and right arrow keys are bound to next/previous track. I looked at the code a bit to see if I could take a crack at a PR, but couldn't wrap my head around how to ignore key press events that **don't** contain modifiers.

**Comment by metalex9** [comment]
Thanks for logging this - I'll get it fixed by the next release!

**Comment by metalex9** [comment]
I'd never heard of [`KeyboardEvent.getModfierState()`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState) before but that's what I used for this.

Here's the commit: https://github.com/generative-music/generative.fm/commit/6ea3d4b82738900b33e10e1863efa43c085aaa45.

Will get pushed out with v1.5.0 on Sunday at the latest.
