### ISSUE TITLE
Add piece loading indicator

### ISSUE THREAD

**Issue by metalex9** [generative-music/generative.fm#17]
Need to display when pieces are loading vs playing.

**Comment by cdtinney** [comment]
Is help wanted on any of these issues?

**Comment by metalex9** [comment]
@cdtinney I appreciate you're willingness to help. I'll be tagging any issues with the "help wanted" label if that's the case, which probably won't be very often for the time being. [See CONTRIBUTING.md](https://github.com/generative-music/generative.fm/blob/master/.github/CONTRIBUTING.md).
