### ISSUE TITLE
Sleep Timer

### ISSUE THREAD

**Issue by metalex9** [generative-music/generative.fm#19]
Suggestion from email to add a sleep timer to the site

**Comment by metalex9** [comment]
I want to try something a little different with this. I've launched a Patreon so people can help with the hosting costs for the site if they feel so inclined. I'd also like to use Patrons to help plan out features like this one. So, [here's a link to the suggestion/feedback thread for this feature on Patreon](https://www.patreon.com/posts/sleep-timer-26203110).

Of course, feel free to leave comments here as well, but the Patreon thread will be given preference.

**Comment by rubo77** [comment]
Maybe you can add a lower basic "Tier" I think 2$ a month for one person is far too much.

micropayment would be fine, I would become a Patreon for 0.10$ a month

**Comment by metalex9** [comment]
Sorry, Patreon only allows increments of $1. Don't feel like you have to pledge anything.

**Comment by TheunisKotze** [comment]
Crypto donations could also be an option for smaller payments.
