### ISSUE TITLE
Move the update button to the tab bar

### ISSUE THREAD

**Issue by j-f1** [generative-music/generative.fm#194]
Currently, in order to update the app, you have to navigate to the About tab, click the update button, then navigate back to the Play tab. Would it make sense to add the update button to the tab bar when an update is available so it can be installed without having to switch back and forth between tabs?

**Comment by metalex9** [comment]
It's definitely not in a good spot right now. I'd like to move it somewhere like the tab bar so you can upgrade in one click.

**Comment by metalex9** [comment]
Done :heavy_check_mark:
