### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by metalex9** [generative-music/generative.fm#20]
Add tags to pieces, such as "ambient," "calm," "piano," etc. This will help users choose a piece to listen to and also pave the way for other styles of music to be added to the site. Later on, music could be organized by tag.

This information will need to be stored in each piece's manifest file.

- [x] Add tags
- [x] Add filters for tags

**Comment by daubaris** [comment]
Hi @metalex9. Should they be displayed in each card or in a separate section, lets say below header?

**Comment by metalex9** [comment]
Patreon suggestion thread for this feature: https://www.patreon.com/posts/26841611
