### ISSUE TITLE
📢 Generative.fm Status Update (May 2020)

### ISSUE THREAD

**Issue by metalex9** [generative-music/generative.fm#205]
Hey folks, just wanted to post something for anyone who finds themselves poking around the repo. My lack of activity here has left some wondering if I've abandoned the project—not at all!

After building Generative.fm to suit my own personal needs, then revamping it several times (once before showing friends and family, once before showing the public, and once more after receiving feedback from the earliest users), I realized the Generative.fm I built before is not the Generative.fm I want it to be now. It's time to start fresh.

I'm completely redesigning and rebuilding the site from scratch. This way I can include all the features I want from the get-go instead of trying to shoehorn them into an existing codebase.

**Please continue to open issues, vote, comment on things, etc. I'm watching them and incorporating them as necessary into the new design.**

If you want to follow along, I'm posting updates (such as design prototypes) and gathering feedback through [my Patreon](https://www.patreon.com/alexbainter). Otherwise, I'll be releasing early access versions of things when they're ready. I don't have any timeline estimates.

Thanks!

**Comment by alexbainter** [comment]
Repo for the new player: https://github.com/generative-fm/play
