### ISSUE TITLE
"Experiencing audio issues?" Flow

### ISSUE THREAD

**Issue by metalex9** [generative-music/generative.fm#21]
Add a small guide for users experiencing audio issues with things to try:
1. (computer) turn the site volume down and your computer volume up.
2. Use a more powerful device. If on mobile, recommend using a computer.
3. Finally, report the issue.

**Comment by coryBove** [comment]
I was on mobile and experiencing some popping, stop/starting, and lag. Using 1 from above seemed to solve the issue. I turned the volume on my phone to its lowest setting, and turned my speakers way up.

Awesome work! Sounds great!

**Comment by metalex9** [comment]
@coryBove Thanks for your feedback, I added your suggestion to the site for mobile developers.

Resolved in #36.
