### ISSUE TITLE
Where do the piano samples come from?

### ISSUE THREAD

**Issue by schollz** [generative-music/generative.fm#25]
The piano song is amazing! I'm curious on where the piano note sounds come from. 

Also, curious what sounds you recorded yourself and how you did that! Very cool project.

**Comment by metalex9** [comment]
Hi @schollz, thanks for the kind words. Most of the samples (including the piano) come from the [Community Edition of Versilian Studios Chamber Orchestra 2](https://vis.versilstudios.com/vsco-community.html). So far the only samples I've recorded myself are the sounds for "Otherness," which are recordings of my electric guitar into a patch of the same name which came stock on my Line 6 POD HD500X, as well as the acoustic guitar samples on "Townsend," which is just my acoustic guitar recorded with a Rhode NT1-A into a Focusrite Scarlett 2i4.

**Comment by metalex9** [comment]
You can find all of the samples that are currently in use [here](https://github.com/generative-music/samples.generative.fm/tree/master/src/samples).

**Comment by schollz** [comment]
Thanks @metalex9. That is some amazing effort, and it really pays off! Very inspiring work.
