### ISSUE TITLE
stop the redirect to the root URL

### ISSUE THREAD

**Issue by waldenn** [generative-music/generative.fm#33]
Hi, thanks for a fascinating project!

I just installed all the code and samples on my own server, and its all working fine: https://wikischool.org/gfm.html

The only thing I can't seem to figure out (perhaps because I'm not that knowledgeable about service-workers), is that when one visits the URL, there is a redirect to the root URL. Where can I prevent that from happening?

Thanks.

**Comment by cdtinney** [comment]
Probably this line:

```
                <Route render={() => <Redirect to="/" />} />
```

This redirects all routes that don't match the defined routes to `/`.

https://github.com/generative-music/generative.fm/blob/master/src/components/app/index.jsx#L35

**Comment by waldenn** [comment]
Thanks, I tried changing those routing lines, but the same redirection behavior persists.
