### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by lwky** [generative-music/generative.fm#35]
Original issue: Most websites I use for background music(youtube, soundcloud) use spacebar to pause or resume the audio, would be great if this site would have it too.

EDIT:
- [x] Space for play/pause
- [x] Right arrow for next
- [x] Left arrow for previous
- [x] Scroll wheel controls volume if the mouse is over the volume control

**Comment by rossvz** [comment]
I noticed this as well! I've opened a PR that adds keyboard event listeners, but not sure if it will be implemented: https://github.com/generative-music/generative.fm/pull/45
