### ISSUE TITLE
Allow output to be streamed to arbitrary endpoints (Sonos, VLC, etc)

### ISSUE THREAD

**Issue by conleyedwards** [generative-music/generative.fm#59]
Would it be possible to provide an mp3 (or other format) stream that could be opened via any audio application - mainly thinking of Sonos here, or other similar devices?

**Comment by metalex9** [comment]
Hi @conleyedwards. There was some discussion around this in #34. If you mean for me to host the streams somewhere, it's certainly possible but would require the compute time for generating the audio and also bandwidth and distribution for the streams, which would be too expensive for me to really consider right now.

A more likely option (which was also discussed in #34) would be for me to provide the stream generation software which you could then use to host the streams yourself (for example, on your own local network). Would that work for you?

**Comment by conleyedwards** [comment]
That could work!  Thanks for the response, appreciate it.

I have a raspberry pi on my network - is this something that could be packaged up and run on something like that?

I think as long as it could write the output to a m3u or mp3 file it could then be streamed to Sonos, other speakers, etc.

**Comment by metalex9** [comment]
I'm tentatively planning on making this and #26 my top priority after [v1.0.0](https://github.com/generative-music/generative.fm/milestone/10) is released.

**Comment by metalex9** [comment]
I'm closing this issue now that [stream.generative.fm](https://github.com/generative-music/stream.generative.fm) has been created. I will update this issue again when that's actually ready to use.
