### ISSUE TITLE
Safari: Controls obscure last row of pieces

### ISSUE THREAD

**Issue by co16353sidak** [generative-music/generative.fm#61]
The fixed bottom media controls bar at the bottom is the best way this could have been implemented but unfortunately due to this, the last row of elements get obscured by the control bar
This makes reading the contents difficult.
Could be an easy fix by implementing a bottom padding to the end of the unfixed page so that the bar lies on empty space the we scroll towards the end of the contents.
Would love to work on this and give out some iterations seeing as it is not a major feature request but a minor bug.

<img width="1280" alt="Screenshot 2019-03-26 at 3 13 57 PM" src="https://user-images.githubusercontent.com/35738138/54987025-c9951900-4fd9-11e9-8872-f174ba5cadf6.png">

**Comment by metalex9** [comment]
I haven't seen this, can you tell me about your environment? Which browser is that screenshot from?

**Comment by metalex9** [comment]
Not seeing this in Chrome 73 or Firefox 59.

**Comment by co16353sidak** [comment]
Running this on macOS Safari, i will send the exact specs to you in a minute

**Comment by metalex9** [comment]
Ah yep, I see it in Safari. I'm gonna take this one since it's a little more nuanced than just adding padding to the bottom.

**Comment by metalex9** [comment]
Also because I forgot to say it earlier: Thank you!

**Comment by co16353sidak** [comment]
I am not giving up on the hope of submitting a PR here though, I will keep on working on this 😄 @metalex9

**Comment by metalex9** [comment]
Okay so this actually was a pretty simple `padding-bottom` fix: https://github.com/generative-music/generative.fm/commit/8ed60d60cb33539ac0701e87d32ea9de119379e2.

I don't know why every browser but Safari was cool with `margin-bottom` instead of `padding-bottom` though. Whatever, fixed in next release!
