### ISSUE TITLE
Implement mediaSession api to support pause, next, etc

### ISSUE THREAD

**Issue by ryanramage** [generative-music/generative.fm#62]
I listen to generative.fm on my mobile android via a bluetooth headset. It would be amazing if I could pause and do next track with my bluetooth controls. I have tested the mediaSession api, and it easily supports this. It would be amazing if generative.fm added this. Here is an example of it working, with code snippets. 

https://googlechrome.github.io/samples/media-session/audio.html

I would be up for doing a pull request if you'd like. 

Thanks!

**Comment by metalex9** [comment]
Nice, this should quick with a Redux middleware. I'm going to see if I can squeeze it into the [next release](https://github.com/generative-music/generative.fm/milestone/2).

**Comment by ryanramage** [comment]
ok, it was a little harder. One issue is that the mediaSession api only works on audio tags currently. So this is what what I got working. I added the following into index.jsx.  Understanding the following

 - an audio tag is added to the dom that just plays silence. This is ugly, but it works
 - the audio tag is looped when ended so we can keep audio focus
 - The user has to do a gesture before the silence begins. Once the gesture is performed then chrome will show the playing icon in the status bar.
 - I can get next to work, but I cant get the play/pause to work. Maybe I am dispatching the wrong action?

```
if (navigator.mediaSession) {

  function playAudio() {
    var audio = document.createElement('audio');
    audio.src = './silence.mp3'; // silence must be at least 5 seconds https://freesound.org/people/silentspeaker/sounds/426895/

    // to keep the controls open, must loop
    audio.addEventListener('ended', function() {
      this.currentTime = 0;
      this.play();
    }, false);

    audio.play().then(_ => {
      navigator.mediaSession.setActionHandler('play', function() {
        console.log('play');
        store.dispatch(play());
      });
      navigator.mediaSession.setActionHandler('pause', function() {
        console.log('Pause');
        store.dispatch(play());
      });
      navigator.mediaSession.setActionHandler('nexttrack', function() {
        console.log('next');
        store.dispatch(next());
      });
    }).catch(error => { console.log(error); });
  }
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('.control-button').forEach(b => {
      b.addEventListener('click', playAudio)
    })
  })
}
```

**Comment by metalex9** [comment]
That is super helpful research, thanks. The silent audio is not an issue, that was actually the same hack I had to do to get audio to behave on iOS devices.
