### ISSUE TITLE
Add new piece: Butterfingers

### ISSUE THREAD

**Issue by metalex9** [generative-music/generative.fm#66]
- [x] Update samples.generative.fm
- [x] Update generator-piece
- [x] Update pieces-alex-bainter
- [x] Update generative.fm

**Comment by lambdaupb** [comment]
I nominate "endless drone" that was available on the opus examples page of xiph.org

http://opus-codec.org/examples/

possibly based on http://boodler.org/package/com.azulebanana.buddhaagent/
