### ISSUE TITLE
Mobile application

### ISSUE THREAD

**Issue by igorobets** [generative-music/generative.fm#67]
Hi 
I like your work and very impressed with the result. Can you pack it into a mobile application to allow listening to music when no internet connection(for example when commuting in the underground)?

I want to buy an application like this for a few dollars.

**Comment by metalex9** [comment]
Hi @igorobets. I haven't communicated this properly but the site will work offline in most modern browsers. However, you must play a piece once online for it to work offline. Eventually all of this will be clear in the app, see #37.
