### ISSUE TITLE
Add keyboard shortcut for mute

### ISSUE THREAD

**Issue by stolksdorf** [generative-music/generative.fm#69]
Original: #35 Added some great keyboard shortcuts, but I would love it if you could use `m` as mute/unmute. This is what youtube uses.

Thanks again for this wonderful site.

EDIT:
- [x] Refactor keyboard shortcuts into a Redux middleware
- [x] Add `m` shortcut for toggling mute

**Comment by metalex9** [comment]
I checked to see what some other sites were doing and found Spotify uses Ctrl-Shift-Down (yuck) and Google Play Music doesn't even have a shortcut for this. I think `m` is a good choice. I'll do that unless someone thinks a different key would be better. Great suggestion, thanks!

**Comment by stolksdorf** [comment]
For context: When you unpause/play a track it sometimes takes a little bit to "get going" again, so I'd like to use mute/unmute to quickly pause/unpause without interrupting the flow of the track that much.

**Comment by metalex9** [comment]
I've been using this so much since it was added, really great suggestion! I do the same thing as you where I mute/unmute instead of stopping and restarting a piece, and this makes it that much easier.
