### ISSUE TITLE
add share urls feature

### ISSUE THREAD

**Issue by rtpHarry** [generative-music/generative.fm#71]
Seems it is in there somewhere as I arrived her from the medium article on generating the aphex twin song and it was the only song listed.

Now I wanted to share the didgeridoo beats on with my friend and cannot get at it as a direct url?

**Comment by metalex9** [comment]
I will add a button or it, but for now you can construct your own by doing `generative.fm/music/alex-bainter-lower-kebab-case-of-piece-name`.

For example:
- [`generative.fm/music/alex-bainter-didgeridoobeats`](https://generative.fm/music/alex-bainter-didgeridoobeats)
- [`generative.fm/music/alex-bainter-a-viable-system`](https://generative.fm/music/alex-bainter-a-viable-system)
- [`generative.fm/music/alex-bainter-timbral-oscillations`](https://generative.fm/music/alex-bainter-timbral-oscillations)
- [`generative.fm/music/alex-bainter-aisatsana`](https://generative.fm/music/alex-bainter-aisatsana)

**Comment by denishowe** [comment]
Could you use [history.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) to update the URL?
