### ISSUE TITLE
aisatsana seems to play the same all the time

### ISSUE THREAD

**Issue by rubo77** [generative-music/generative.fm#79]
I read [this article](https://nerdcore.de/2019/03/27/unendlicher-aphex-twin-track/?fbclid=IwAR1AoQQPuFA5Aql2voQFdkbRD1-500yMWNUSlTHN6jtW22D9NgbaNwGeczQ) and followed this link:
https://generative.fm/music/alex-bainter-aisatsana

Now it seems like the track is not changing a lot at all, it plays the same over and over again. Also it doesn't sound like "Aphex Twin" at all. Is this intended?

I am full of joyfull expectations to hear an enhancement there ;)

**Comment by metalex9** [comment]
Does it sound like [this](https://www.youtube.com/watch?v=3_MRe3JwFc8)?

**Comment by rubo77** [comment]
Yes ;)

I didn't know that aphex twins also does such calm songs.

But anyway, does the song loop in a way? Or are the sounds always different?

**Comment by metalex9** [comment]
It randomly selects one phrase to play from over 4 million possible phrases each time. You can read all about how it works here: https://medium.com/@metalex9/generating-more-of-my-favorite-aphex-twin-track-cde9b7ecda3a
